### PR TITLE
8277890: riscv: fix the infinite LR/SC loop in BarrierSetAssembler::eden_allocate

### PR DESCRIPTION
**Pull request by yadongw**
This bug can be reproduced by `java -XX:+UseSerialGC -XX:-UseTLAB -XX:TieredStopAtLevel=1 -version` on the unmatched board where this command will hang. The reason is that the implementation of load reserved/store conditional loop in BarrierSetAssembler::eden_allocate breaks the RISC-V Atomic extension spec:
```
For the
sequence to be guaranteed to eventually succeed, the dynamic code executed between the LR and
SC instructions can only contain other instructions from the base \I" subset, excluding loads, stores,
backward jumps or taken backward branches, FENCE, FENCE.I, and SYSTEM instructions.
```
It may cause an unspecified behaviour depends on specific hardware implementations.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277890](https://bugs.openjdk.java.net/browse/JDK-8277890): riscv: fix the infinite LR/SC loop in BarrierSetAssembler::eden_allocate

### Reviewers
 * [Fei Yang](https://openjdk.java.net/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/riscv-port pull/17/head:pull/17` \
`$ git checkout pull/17`

Update a local copy of the PR: \
`$ git checkout pull/17` \
`$ git pull https://git.openjdk.java.net/riscv-port pull/17/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17`

View PR using the GUI difftool: \
`$ git pr show -t 17`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/riscv-port/pull/17.diff">https://git.openjdk.java.net/riscv-port/pull/17.diff</a>

</details>

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
Looks good. Thanks for fixing this :-)

**Comment by zhengxiaolinX** [comment]
Thank you for fixing this. Qemu and C910 cannot reveal this issue so I didn't notice it.  :-(   
I just tested this `-XX:+UseSerialGC -XX:-UseTLAB -XX:TieredStopAtLevel=1` on both a D1 and an unleashed board, and this issue was reproduced without this patch.

No need to reply -- it is just a comment.

**Pull request closed without merging**
