### PR TITLE
8280423: riscv: Unnecessary i2l conversion in LIRGenerator::emit_array_address

### PR DESCRIPTION
**Pull request by feilongjiang**
On RISC-V, operands with `T_INT` type are sign-extended implicitly when defined, so i2l conversion is unnecessary.
This fix is similar with JDK-8278417, which calls generate_address directly to generate address for array access.

All jtregs were tested on QEMU without new failures.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8280423](https://bugs.openjdk.java.net/browse/JDK-8280423): riscv: Unnecessary i2l conversion in LIRGenerator::emit_array_address

### Reviewers
 * [Fei Yang](https://openjdk.java.net/census#fyang) (@RealFYang - **Reviewer**)
 * [Yanhong Zhu](https://openjdk.java.net/census#yzhu) (@yhzhu20 - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/riscv-port pull/51/head:pull/51` \
`$ git checkout pull/51`

Update a local copy of the PR: \
`$ git checkout pull/51` \
`$ git pull https://git.openjdk.java.net/riscv-port pull/51/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 51`

View PR using the GUI difftool: \
`$ git pr show -t 51`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/riscv-port/pull/51.diff">https://git.openjdk.java.net/riscv-port/pull/51.diff</a>

</details>

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
Looks reasonable.

**Review by yhzhu20 — APPROVED** [review]
Looks good.

**Comment by feilongjiang** [comment]
Thanks for the reviews. @RealFYang @yhzhu20
/integrate

**Pull request closed without merging**
