### PR TITLE
8279565: riscv: RVB: Add byte reverse instruction

### PR DESCRIPTION
**Pull request by feilongjiang**
This PR has the following changes:
1. Implement byte-reverse instruction `rev8` of RISC-V BitManipulation Extension.
2. Code improvement of existing byte reverse methods. 
3. Merge assembler_riscv_b.hpp and assembler_riscv_v.hpp into assembler_riscv.hpp

Renaming of byte reverse methods is based on BitManipulation v0.93 [[1]], which provides `rev8.h`, `rev8.w` and `rev8` to reverse bytes in halfwords, words, and doubleword respectively. However, there are still some byte reverse operations that are not covered by spec, for example, "reverse bytes in halfword in lower 16 bits and sign extend". Base on the existing instructions naming style, we use `rev8.h.h` to represent it.

New C2 instructions under riscv_b.ad are covered by the following JTREG tests:
- test/hotspot/jtreg/compiler/codegen/Test6431242.java
- test/hotspot/jtreg/compiler/c2/TestCharShortByteSwap.java

Hotspot and jdk tier1 tests on QEMU (with and without UseRVB) are passed without new failures.

[1]: https://github.com/riscv/riscv-bitmanip/releases/download/v0.93/bitmanip-0.93.pdf

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8279565](https://bugs.openjdk.java.net/browse/JDK-8279565): riscv: RVB: Add byte reverse instruction

### Reviewers
 * [Fei Yang](https://openjdk.java.net/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/riscv-port pull/42/head:pull/42` \
`$ git checkout pull/42`

Update a local copy of the PR: \
`$ git checkout pull/42` \
`$ git pull https://git.openjdk.java.net/riscv-port pull/42/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 42`

View PR using the GUI difftool: \
`$ git pr show -t 42`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/riscv-port/pull/42.diff">https://git.openjdk.java.net/riscv-port/pull/42.diff</a>

</details>

### CODE REVIEW

**Comment by feilongjiang** [comment]
Rebased riscv-port branch with no conflicts, hotspot tier1 passed on QEMU with  UseRVB without new failures.

**Review by RealFYang — APPROVED** [review]
Looks good. Thanks.

**Comment by feilongjiang** [comment]
Thanks for your reviews, Felix.
/integrate

**Pull request closed without merging**
