### PR TITLE
8282415: riscv: Rename StubRoutines::riscv64 to StubRoutines::riscv

### PR DESCRIPTION
**Pull request by feilongjiang**
Rename `SubRoutine::riscv64` to `SubRoutine::riscv`, just like the PPC64 port.

Tier1 tests on QEMU are passed without new faliures.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282415](https://bugs.openjdk.java.net/browse/JDK-8282415): riscv: Rename StubRoutines::riscv64 to StubRoutines::riscv

### Reviewers
 * [Yanhong Zhu](https://openjdk.java.net/census#yzhu) (@yhzhu20 - Committer)
 * [Fei Yang](https://openjdk.java.net/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/riscv-port pull/60/head:pull/60` \
`$ git checkout pull/60`

Update a local copy of the PR: \
`$ git checkout pull/60` \
`$ git pull https://git.openjdk.java.net/riscv-port pull/60/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 60`

View PR using the GUI difftool: \
`$ git pr show -t 60`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/riscv-port/pull/60.diff">https://git.openjdk.java.net/riscv-port/pull/60.diff</a>

</details>

### CODE REVIEW

**Review by yhzhu20 — APPROVED** [review]
Looks good to me.

**Review by RealFYang — APPROVED** [review]
This will make the code more consistent. Thanks.

**Comment by feilongjiang** [comment]
Thanks for the reviews😀@yhzhu20 @RealFYang 
/integrate

**Pull request closed without merging**
